backend: "python"
input [
    {
        name: "messages"
        data_type: TYPE_STRING
        dims: [ 1 ]
    },
    {
        name: "max_new_tokens"
        data_type: TYPE_INT32
        optional: true
        dims: [ 1 ]
    }
]
output [
    {
        name: "generated_text"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

parameters {
  key: "model_path"
  value: {
    string_value: "/workspace/model"
  }
}

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
